theme: jekyll-theme-dinky
title: Mihai Tudoroiu
description:           
    My personal blog.                             
    Feel free to bookmark this to keep an eye on my project updates.

email: mihaitudo@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url:                   https://mihaitudoroiu.github.io
lang:                  en
linkedin_username: Mihai Tudoroiu
github_username:  MihaiTudoroiu

plugins:
  - jekyll-feed
  
copyright:             Â© 2021. All rights reserved.
